status_node:
  ros__parameters:
    sampling_frequency: 100.0
    data_at_sampling_frequency: true
    position: false
    velocity: false
    torque: false
    pose: true
    ft: false
    base_path: '/home/svaya/Desktop/rde_darm_testing/src/dual_arm_utilities/data'
    file_name: '200sk_w_blending'
    blending_params_f: false
    pose_error_f: true
    torque_d_f: false
    torque_a_f: false
    
